%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Github\Narrowband-Wideband\multi-frequency\Design_narrow_band.txt
%
% Auto-generated by MATLAB on 10-Aug-2024 09:37:08

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ["\t", ","];

% Specify column name
% s and types
opts.VariableNames = ["Freq", "Vout1", "Var3", "Vout2", "Var5"];
opts.SelectedVariableNames = ["Freq", "Vout1", "Vout2"];
opts.VariableTypes = ["double", "double", "string", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var3", "Var5"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var3", "Var5"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["Vout1", "Vout2"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["Vout1", "Vout2"], "ThousandsSeparator", ",");

% Import the data
tbl = readtable("C:\Github\Narrowband-Wideband\multi-frequency\Design_wide_band - Copy.txt", opts);

%% Convert to output type
Freq = tbl.Freq;
Vout1 = tbl.Vout1;
Vout2 = tbl.Vout2;

%% Clear temporary variables
clear opts tbl